#29-Inserting-data-in-table
hrvojeBencik/first_drupal_project pull request #11
Opened 2021-02-08 10:23 UTC by hrvojeBencik

After choosing movie, day and entering customer name data is passed with the URL and inserted into table 'reservations'.

2021-02-08 10:33 UTC, DarioPMM commented on web/modules/custom/movie/movie.module
> +
Što prazni redovi?

2021-02-08 10:35 UTC, hrvojeBencik commented on web/modules/custom/movie/movie.module
> +
Ostalo mi je od pre, kada sam isprobavao nesto u tom fajlu, ispravicu.

2021-02-08 10:50 UTC, DarioPMM commented on web/modules/custom/movie/src/Controller/MovieController.php
> +    $customerName = \Drupal::request()->request->get('customerName');
Postoji li opcija da se formira niz koji ce biti u requestu, pa da se odradi jedan request->get() i da se odatle izvlace podaci? Da li je po tebi bolje ovako sa 4 get-a ili s 1 get-om?

2021-02-08 10:51 UTC, DarioPMM commented on web/modules/custom/movie/src/Controller/MovieController.php
> +    if($movieGenre != NULL && $movieName != NULL && $customerName != NULL && $day != NULL) {
Pogledati razliku izmedju '==' i '===' i iskoristiti bolji od ta dva za ovaj slucaj koji ti imas.

2021-02-08 10:52 UTC, DarioPMM commented on web/modules/custom/movie/src/Controller/MovieController.php
> +      $conn = \Drupal::database();
Definicija variabli i funkcija bi trebala uvek biti jasna. Zamisli da radis na nekom projektu i dodje novi kolega i treba da ispravi nesto u ovom kodu. Da li bi tebi bilo skroz jasno sta znaci conn?

2021-02-08 10:57 UTC, DarioPMM commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
Ovaj nacin slanja podataka bi trebalo izmeniti. Jer je vidljivo iz inspecta sta se salje i na koju rutu. Bolja ideja je da se na submit buttona pozove preko jQuery jedna funkcija, koja ce da pokupi vrednosti preko .val() (ili sta ti vec treba) i onda ce u toj funkciji da se salje ajaksom dalje gde treba.

2021-02-08 10:57 UTC, DarioPMM requested changes
Potrebno je adresirati komentare.

2021-02-08 11:04 UTC, hrvojeBencik commented on web/modules/custom/movie/src/Controller/MovieController.php
> +    $customerName = \Drupal::request()->request->get('customerName');
Bolji je jedan get naravno, uradicu tako.

2021-02-08 11:05 UTC, hrvojeBencik commented on web/modules/custom/movie/src/Controller/MovieController.php
> +    if($movieGenre != NULL && $movieName != NULL && $customerName != NULL && $day != NULL) {
Kada imamo '===' proverava se i tip varijable a ne samo vrednost

2021-02-08 11:06 UTC, hrvojeBencik commented on web/modules/custom/movie/src/Controller/MovieController.php
> +      $conn = \Drupal::database();
@DarioPMM Promenicu u $dbConnection

2021-02-08 11:50 UTC, hrvojeBencik commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@DarioPMM Da li da bih pozivao jQuery funckiju  i posle koristio AJAX moram napraviti formu u posebnoj klasi pa je tako upotrebiti? Mislim na klasu koja nasledjuje FormBase

2021-02-08 12:02 UTC, DarioPMM commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@hrvojeBencik mozes li da mi pojasnis gde bi stavio tu posebnu klasu?

2021-02-08 12:26 UTC, hrvojeBencik commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@DarioPMM Pa nasao sam na internetu na vise sajtova primere, isla bi u movie/src/Form/ReservationForm.php

2021-02-08 12:37 UTC, DarioPMM commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@hrvojeBencik mislim da je najbolje da mi posaljes neki link i ukazes na sta mislis, da budemo sigurni da se razumemo. :)

2021-02-08 12:39 UTC, hrvojeBencik commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@DarioPMM To bi bilo ovako nesto, https://www.drupal.org/docs/drupal-apis/javascript-api/ajax-forms. Mada treba modifikovati formu i nekako napravaiti funkciju koja uzima vrednosti iz forma i izvrsava insert.

2021-02-08 12:43 UTC, DarioPMM commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@hrvojeBencik ne moras novu formu praviti. Na stranici na kojoj si vec imas dovoljno podataka. Samo pokupi odatle u prosledi ih u ajaxu, pa kasnije upisi u bazu.

2021-02-08 12:45 UTC, hrvojeBencik commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@DarioPMM Ok, da li bi mi mogao dati neki link za to sto mi treba, jer nisam uspeo pronaci do sada?

2021-02-09 08:49 UTC, hrvojeBencik commented on web/modules/custom/movie/templates/movie-theme-hook.html.twig
> +    <form action="/movie-reservation?movieName={{ movie.label }}&genre={{ movie.field_genre.0.entity.name.value }}" method="post">
@DarioPMM Pokupio sam podatke preko jQuery-a i prosledio ih Ajax-om do kontrolera, odatle se izvrsila funckija inserta u bazu. Izvrsava se samo jedan POST request, jer su podaci prosledjeni kao niz koncertovan u JSON.

2021-02-09 10:06 UTC, DarioPMM commented on web/modules/custom/movie/js/movie-reservation.js
> +  let submit = $('#submit');
Da li ovo mora da bude let (kao i sve ove ispod)?

2021-02-09 10:08 UTC, hrvojeBencik commented on web/modules/custom/movie/js/movie-reservation.js
> +  let submit = $('#submit');
@DarioPMM  S obzirom da se nece menjati kasnije, ne mora, moze i const

2021-02-09 10:08 UTC, DarioPMM commented on web/modules/custom/movie/src/Controller/MovieController.php
> +              $movieData[2],
Ono sto bi bilo dobro (posto ja sad na prvi pogled ne znam sta je koji elemnt po redu u movieData), da pise $movieData['genre']. $movieData['name'] itd... Da li je moguce?

2021-02-09 10:10 UTC, hrvojeBencik commented on web/modules/custom/movie/src/Controller/MovieController.php
> +              $movieData[2],
@DarioPMM Moguce je, ispravicu

2021-02-09 11:24 UTC, DarioPMM approved these changes

2021-02-09 11:25 UTC, merged